Update nginx
- formatting

diff --git a/rootfs_files/etc/init.d/nginx b/rootfs_files/etc/init.d/nginx
--- a/rootfs_files/etc/init.d/nginx
+++ b/rootfs_files/etc/init.d/nginx
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 ### BEGIN INIT INFO
-# Provides:	  nginx
+# Provides:          nginx
 # Required-Start:    $local_fs $remote_fs $network $syslog $named
 # Required-Stop:     $local_fs $remote_fs $network $syslog $named
 # Default-Start:     2 3 4 5
@@ -17,7 +17,7 @@ DESC=nginx
 
 # Include nginx defaults if available
 if [ -r /etc/default/nginx ]; then
-	. /etc/default/nginx
+  . /etc/default/nginx
 fi
 
 STOP_SCHEDULE="${STOP_SCHEDULE:-QUIT/5/TERM/5/KILL/5}"
@@ -30,12 +30,12 @@ test -x $DAEMON || exit 0
 # Try to extract nginx pidfile
 PID=$(cat /etc/nginx/nginx.conf | grep -Ev '^\s*#' | awk 'BEGIN { RS="[;{}]" } { if ($1 == "pid") print $2 }' | head -n1)
 if [ -z "$PID" ]; then
-	PID=/run/nginx.pid
+  PID=/run/nginx.pid
 fi
 
 if [ -n "$ULIMIT" ]; then
-	# Set ulimit if it is set in /etc/default/nginx
-	ulimit $ULIMIT
+  # Set ulimit if it is set in /etc/default/nginx
+  ulimit $ULIMIT
 fi
 
 # MOS custom: update Frontend
@@ -50,7 +50,7 @@ mos_update_frontend() {
   FRONTEND_ASSET_ID=$(echo $FRONTEND_JSON | jq -r '.assets[] | select(.name | startswith("mos-frontend") and endswith(".tar.gz")) | .id')
 
   # Remove WebUI
-	rm -rf /var/www/assets /var/www/index.html /var/www/mos* 2>/dev/null
+  rm -rf /var/www/assets /var/www/index.html /var/www/mos* 2>/dev/null
 
   # Download and extract new WebUI
   curl --progress-bar -L \
@@ -60,193 +60,191 @@ mos_update_frontend() {
     --output "/tmp/frontend.tar.gz" \
     "https://api.github.com/repos/ich777/mos-frontend/releases/assets/$FRONTEND_ASSET_ID"
   tar -C /var/www/ -xf /tmp/frontend.tar.gz
-	rm -rf /tmp/frontend.tar.gz
+  rm -rf /tmp/frontend.tar.gz
 
   jq --arg frontend_v "${FRONTEND_V}_updated" '.mos.frontend = $frontend_v' /etc/mos-release.json > /etc/mos-release.json.tmp && mv /etc/mos-release.json.tmp /etc/mos-release.json
 }
 
 start_nginx() {
-	# Start the daemon/service
-	#
-	# Returns:
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
+  # Start the daemon/service
+  #
+  # Returns:
+  #   0 if daemon has been started
+  #   1 if daemon was already running
+  #   2 if daemon could not be started
 
-	mkdir -p /var/log/nginx >/dev/null 2>&1
+  mkdir -p /var/log/nginx >/dev/null 2>&1
 
-	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- \
-		$DAEMON_OPTS 2>/dev/null \
-		|| return 2
+  start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null || return 1
+  start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- \
+    $DAEMON_OPTS 2>/dev/null || return 2
 }
 
 test_config() {
-	# Test the nginx configuration
-	$DAEMON -t $DAEMON_OPTS >/dev/null 2>&1
+  # Test the nginx configuration
+  $DAEMON -t $DAEMON_OPTS >/dev/null 2>&1
 }
 
 stop_nginx() {
-	# Stops the daemon/service
-	#
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=$STOP_SCHEDULE --pidfile $PID --name $NAME
-	RETVAL="$?"
-	sleep 1
-	return "$RETVAL"
+  # Stops the daemon/service
+  #
+  # Return
+  #   0 if daemon has been stopped
+  #   1 if daemon was already stopped
+  #   2 if daemon could not be stopped
+  #   other if a failure occurred
+  start-stop-daemon --stop --quiet --retry=$STOP_SCHEDULE --pidfile $PID --name $NAME
+  RETVAL="$?"
+  sleep 1
+  return "$RETVAL"
 }
 
 reload_nginx() {
-	# Function that sends a SIGHUP to the daemon/service
-	start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
-	return 0
+  # Function that sends a SIGHUP to the daemon/service
+  start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
+  return 0
 }
 
 rotate_logs() {
-	# Rotate log files
-	start-stop-daemon --stop --signal USR1 --quiet --pidfile $PID --name $NAME
-	return 0
+  # Rotate log files
+  start-stop-daemon --stop --signal USR1 --quiet --pidfile $PID --name $NAME
+  return 0
 }
 
 upgrade_nginx() {
-	# Online upgrade nginx executable
-	# http://nginx.org/en/docs/control.html
-	#
-	# Return
-	#   0 if nginx has been successfully upgraded
-	#   1 if nginx is not running
-	#   2 if the pid files were not created on time
-	#   3 if the old master could not be killed
-	if start-stop-daemon --stop --signal USR2 --quiet --pidfile $PID --name $NAME; then
-		# Wait for both old and new master to write their pid file
-		while [ ! -s "${PID}.oldbin" ] || [ ! -s "${PID}" ]; do
-			cnt=`expr $cnt + 1`
-			if [ $cnt -gt 10 ]; then
-				return 2
-			fi
-			sleep 1
-		done
-		# Everything is ready, gracefully stop the old master
-		if start-stop-daemon --stop --signal QUIT --quiet --pidfile "${PID}.oldbin" --name $NAME; then
-			return 0
-		else
-			return 3
-		fi
-	else
-		return 1
-	fi
+  # Online upgrade nginx executable
+  # http://nginx.org/en/docs/control.html
+  #
+  # Return
+  #   0 if nginx has been successfully upgraded
+  #   1 if nginx is not running
+  #   2 if the pid files were not created on time
+  #   3 if the old master could not be killed
+  if start-stop-daemon --stop --signal USR2 --quiet --pidfile $PID --name $NAME; then
+    # Wait for both old and new master to write their pid file
+    while [ ! -s "${PID}.oldbin" ] || [ ! -s "${PID}" ]; do
+      cnt=`expr $cnt + 1`
+      if [ $cnt -gt 10 ]; then
+        return 2
+      fi
+      sleep 1
+    done
+    # Everything is ready, gracefully stop the old master
+    if start-stop-daemon --stop --signal QUIT --quiet --pidfile "${PID}.oldbin" --name $NAME; then
+      return 0
+    else
+      return 3
+    fi
+  else
+    return 1
+  fi
 }
 
 case "$1" in
-	start)
-		log_daemon_msg "Starting $DESC" "$NAME"
-		start_nginx
-		case "$?" in
-			0|1) log_end_msg 0 ;;
-			2)   log_end_msg 1 ;;
-		esac
-		;;
-	stop)
-		log_daemon_msg "Stopping $DESC" "$NAME"
-		stop_nginx
-		case "$?" in
-			0|1) log_end_msg 0 ;;
-			2)   log_end_msg 1 ;;
-		esac
-		;;
-	restart)
-		log_daemon_msg "Restarting $DESC" "$NAME"
+  start)
+    log_daemon_msg "Starting $DESC" "$NAME"
+    start_nginx
+    case "$?" in
+      0|1) log_end_msg 0 ;;
+      2)   log_end_msg 1 ;;
+    esac
+  ;;
+  stop)
+    log_daemon_msg "Stopping $DESC" "$NAME"
+    stop_nginx
+    case "$?" in
+      0|1) log_end_msg 0 ;;
+      2)   log_end_msg 1 ;;
+    esac
+  ;;
+  restart)
+    log_daemon_msg "Restarting $DESC" "$NAME"
 
-		# Check configuration before stopping nginx
-		if ! test_config; then
-			log_end_msg 1 # Configuration error
-			exit $?
-		fi
+    # Check configuration before stopping nginx
+    if ! test_config; then
+      log_end_msg 1 # Configuration error
+      exit $?
+    fi
 
-		stop_nginx
-		case "$?" in
-			0|1)
-				start_nginx
-				case "$?" in
-					0) log_end_msg 0 ;;
-					1) log_end_msg 1 ;; # Old process is still running
-					*) log_end_msg 1 ;; # Failed to start
-				esac
-				;;
-			*)
-				# Failed to stop
-				log_end_msg 1
-				;;
-		esac
-		;;
-	reload|force-reload)
-		log_daemon_msg "Reloading $DESC configuration" "$NAME"
+    stop_nginx
+    case "$?" in
+      0|1)
+        start_nginx
+        case "$?" in
+          0) log_end_msg 0 ;;
+          1) log_end_msg 1 ;; # Old process is still running
+          *) log_end_msg 1 ;; # Failed to start
+        esac
+      ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+      ;;
+    esac
+  ;;
+  reload|force-reload)
+    log_daemon_msg "Reloading $DESC configuration" "$NAME"
 
-		# Check configuration before stopping nginx
-		#
-		# This is not entirely correct since the on-disk nginx binary
-		# may differ from the in-memory one, but that's not common.
-		# We prefer to check the configuration and return an error
-		# to the administrator.
-		if ! test_config; then
-			log_end_msg 1 # Configuration error
-			exit $?
-		fi
+    # Check configuration before stopping nginx
+    #
+    # This is not entirely correct since the on-disk nginx binary
+    # may differ from the in-memory one, but that's not common.
+    # We prefer to check the configuration and return an error
+    # to the administrator.
+    if ! test_config; then
+      log_end_msg 1 # Configuration error
+      exit $?
+    fi
 
-		reload_nginx
-		log_end_msg $?
-		;;
-	configtest|testconfig)
-		log_daemon_msg "Testing $DESC configuration"
-		test_config
-		log_end_msg $?
-		;;
-	status)
-		status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
-		;;
-	upgrade)
-		log_daemon_msg "Upgrading binary" "$NAME"
-		upgrade_nginx
-		log_end_msg $?
-		;;
-	update)
-		log_daemon_msg "Updating mos-frontend" "$NAME"
+    reload_nginx
+    log_end_msg $?
+  ;;
+  configtest|testconfig)
+    log_daemon_msg "Testing $DESC configuration"
+    test_config
+    log_end_msg $?
+  ;;
+  status)
+    status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
+  ;;
+  upgrade)
+    log_daemon_msg "Upgrading binary" "$NAME"
+    upgrade_nginx
+    log_end_msg $?
+  ;;
+  update)
+    log_daemon_msg "Updating mos-frontend" "$NAME"
 
-		# Check configuration before stopping nginx
-		if ! test_config; then
-			log_end_msg 1 # Configuration error
-			exit $?
-		fi
+    # Check configuration before stopping nginx
+    if ! test_config; then
+      log_end_msg 1 # Configuration error
+      exit $?
+    fi
 
-		stop_nginx
-		case "$?" in
-			0|1)
-			  mos_update_frontend
-				start_nginx
-				case "$?" in
-					0) log_end_msg 0 ;;
-					1) log_end_msg 1 ;; # Old process is still running
-					*) log_end_msg 1 ;; # Failed to start
-				esac
-				;;
-			*)
-				# Failed to stop
-				log_end_msg 1
-				;;
-		esac
-		;;
-	rotate)
-		log_daemon_msg "Re-opening $DESC log files" "$NAME"
-		rotate_logs
-		log_end_msg $?
-		;;
-	*)
-		echo "Usage: $NAME {start|stop|restart|update|reload|force-reload|status|configtest|rotate|upgrade}" >&2
-		exit 3
-		;;
+    stop_nginx
+    case "$?" in
+      0|1)
+        mos_update_frontend
+        start_nginx
+        case "$?" in
+          0) log_end_msg 0 ;;
+          1) log_end_msg 1 ;; # Old process is still running
+          *) log_end_msg 1 ;; # Failed to start
+        esac
+      ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+      ;;
+    esac
+  ;;
+  rotate)
+    log_daemon_msg "Re-opening $DESC log files" "$NAME"
+    rotate_logs
+    log_end_msg $?
+  ;;
+  *)
+    echo "Usage: $NAME {start|stop|restart|update|reload|force-reload|status|configtest|rotate|upgrade}" >&2
+    exit 3
+  ;;
 esac
