Update mos-docker_autostart

diff --git a/rootfs_files/usr/local/bin/mos-docker_autostart b/rootfs_files/usr/local/bin/mos-docker_autostart
--- a/rootfs_files/usr/local/bin/mos-docker_autostart
+++ b/rootfs_files/usr/local/bin/mos-docker_autostart
@@ -1,9 +1,16 @@
 #!/bin/sh
 counter=0
-while ! docker info >/dev/null 2>&1 && [ $counter -lt 15 ]; do
+while ! docker info >/dev/null 2>&1 ; do
+  if [ $counter -ge 15 ]; then
+    logger -t "mos-docker_autostart" "Error: Docker daemon not ready, aborting Container autostart"
+    exit 1
+  fi
   sleep 1
   ((counter++))
 done
+
+sleep 5
+
 AUTOSTART_CONTAINERS=$(jq -r '.[] | select(.autostart == true) | "\(.index):\(.name):\(.wait)"' /var/lib/docker/mos/containers 2>/dev/null | sort -n -t: -k1,1)
 DOCKER_WAIT=$(jq -r '.start_wait' /boot/config/docker.json)
 if [ ! -z "$DOCKER_WAIT" ] && [ "$DOCKER_WAIT" != "null" ] && [ "$DOCKER_WAIT" != "0" ]; then
