Update mos-start

diff --git a/rootfs_files/usr/local/bin/mos-start b/rootfs_files/usr/local/bin/mos-start
--- a/rootfs_files/usr/local/bin/mos-start
+++ b/rootfs_files/usr/local/bin/mos-start
@@ -72,6 +72,49 @@ start_ntp() {
   fi
 }
 
+# Install plugins
+install_plugins() {
+  # Get all plugin directories
+  for plugin in /boot/optional/plugins/*; do
+    # Set installation done and get version paths
+    INSTALLATION_DONE=false
+    VERSION_PATH=$(ls -d $plugin/*/ 2>/dev/null | sort -V | tail -1)
+    if [ ! -z "$VERSION_PATH" ] ; then
+      PACKAGE_PATH=$(ls "$VERSION_PATH"*.deb 2>/dev/null)
+      # If there is not .deb package in Version folder it's proabably not a plugin
+      if [ ! -z "$PACKAGE_PATH" ] ; then
+        DISPLAY_NAME=$(jq -r '.name' $plugin/template.json)
+        logger -t "MOS Plugins: $DISPLAY_NAME" "Installing: ${PACKAGE_PATH##*/}" 
+        DEBIAN_FRONTEND=noninteractive dpkg -i $PACKAGE_PATH >/dev/null 2>&1
+        INSTALLATION_DONE=true
+      fi
+      # Run functions file if found (in subshell to avoid using variables from function in mos-start)
+      if [ -f "$VERSION_PATH/functions" ] ; then
+        (
+          source $VERSION_PATH/functions
+          if type mos-start &>/dev/null ; then
+            logger -t "MOS Plugins: $DISPLAY_NAME" "Executing start script"
+            mos-start 2>&1 | logger -t "MOS Plugins: $DISPLAY_NAME"
+            EXIT_STATUS=${PIPESTATUS[0]}
+            if [ "$EXIT_STATUS" != "0" ] ; then
+              logger -t "MOS Plugins: $DISPLAY_NAME" "ERROR: Running start script"
+              exit 1
+            else
+              logger -t "MOS Plugins: $DISPLAY_NAME" "Start script finished successful"
+              exit 0
+            fi
+          fi
+        )
+        INSTALLATION_DONE=true
+      fi
+    fi
+    if [ "$INSTALLATION_DONE" == "true" ] ; then
+      logger -t "MOS Plugins: $DISPLAY_NAME" "Installation finished"
+    fi
+    unset INSTALLATION_DONE VERSION_PATH PACKAGE_PATH DISPLAY_NAME
+  done
+}
+
 # Start nginx service for the WebUI
 start_nginx() {
   /etc/init.d/nginx start
@@ -438,6 +481,7 @@ if [ "$1" = "os" ] ; then
   start_ntp
   persist_history
   start_ssh
+  install_plugins
   start_tailscale
   start_netbird
   start_iscsi_initiator
