Update mos-os_update
add notifiy messages

diff --git a/rootfs_files/usr/local/bin/mos-os_update b/rootfs_files/usr/local/bin/mos-os_update
--- a/rootfs_files/usr/local/bin/mos-os_update
+++ b/rootfs_files/usr/local/bin/mos-os_update
@@ -13,10 +13,10 @@ rollback_mos() {
 
   # Check if rollback version is in place
   if [ -f /boot/rollback/rootfs ] ; then
-    echo "Rolling back to MOS version: $ROLLBACK_VERSION"
+    echo '{"message":"Rolling back to MOS version: '"$ROLLBACK_VERSION"', please wait...","priority":"normal"}' | nc -U /run/mos-notify.sock
     mv /boot/rollback/rootfs* /boot/
   else
-    echo "ERROR: No MOS release found for rolling back found"
+    echo '{"message":"No MOS release to roll back to found","priority":"alert"}' | nc -U /run/mos-notify.sock
     exit 1
   fi
   
@@ -32,6 +32,7 @@ rollback_mos() {
     fi
   fi
   rm -rf /boot/rollback
+  echo '{"message":"Rollback done, please reboot","priority":"normal"}' | nc -U /run/mos-notify.sock
   exit 0
 }
 
@@ -72,16 +73,20 @@ mkdir -p /tmp/mos-update/update >/dev/null 2>&1
 # Set version depending on which argument is passed over
 if [ "$1" = "latest" ] ; then
   VERSION=$(jq --arg channel "$2" -r '.[] | select(.tag_name | contains($channel)) | .tag_name' /tmp/mos-update/releases.json | sort -V | tail -1)
+  if [ -z "$VERSION" ] ; then
+    echo '{"message":"No latest MOS version in Channel '"$1"' found","priority":"alert"}' | nc -U /run/mos-notify.sock
+    exit 1
+  fi
 else
   VERSION="$1"
 fi
 
 # Display message if upgrading to the same version
 if [ "$VERSION" = "$CURRENT_VERSION" ] ; then
-  echo "Version is the same as the current running MOS version, continung in 10 seconds"
+  echo '{"message":"Version is the same as the current running MOS version, continung in 10 seconds","priority":"warning"}' | nc -U /run/mos-notify.sock
   sleep 10
 else
-  echo "Changing MOS version from: $CURRENT_VERSION to version: $VERSION"
+  echo '{"message":"Changing MOS version from: '"$CURRENT_VERSION"' to version: '"$VERSION"', please wait...","priority":"normal"}' | nc -U /run/mos-notify.sock
 fi
 
 # Get assets ID's from rootfs and md5
@@ -102,7 +107,7 @@ if [ "$3" = "update_kernel" ] ; then
   "https://api.github.com/repos/ich777/mos-rootfs/releases/assets/$ASSET_RELEASE_JSON"
   EXIT_STATUS=$?
   if [ "$EXIT_STATUS" != "0" ] ; then
-    echo "Something went wrong getting recommended Kernel version, not updating Kernel"
+    echo '{"message":"Something went wrong getting recommended Kernel version, not updating Kernel","priority":"warning"}' | nc -U /run/mos-notify.sock
     rm -f /tmp/mos-update/mos-$VERSION.json
     UPDATE_KERNEL="false"
   else
@@ -111,7 +116,7 @@ if [ "$3" = "update_kernel" ] ; then
     RUNNING_KERNEL=$(uname -r)
     # Compare if Kernel needs to be upgraded
     if [ "$RUNNING_KERNEL" != $KERNEL ] ; then
-      echo "New recommended Kernel: $KERNEL"
+      echo '{"message":"Upgrading Kernel to new recommended Kernel: '"$KERNEL"'","priority":"normal"}' | nc -U /run/mos-notify.sock
       curl -s --request GET \
         --url "https://api.github.com/repos/ich777/mos-kernel/releases?per_page=100" \
         --header "Authorization: Bearer $TOKEN" \
@@ -124,7 +129,7 @@ if [ "$3" = "update_kernel" ] ; then
       ASSET_DRIVERS_MD5=$(jq --arg kernel $KERNEL -r '.[] | select(.tag_name == $kernel) | .assets[] | select(.name == "drivers") | .id' /tmp/mos-update/$KERNEL.json)
       UPDATE_KERNEL="true"
     else
-      echo "Kernel $RUNNING_KERNEL alread up-to-date"
+      echo '{"message":"Kernel '"$RUNNING_KERNEL"' alread up-to-date","priority":"normal"}' | nc -U /run/mos-notify.sock
       UPDATE_KERNEL="false"
     fi
   fi
@@ -151,7 +156,7 @@ curl -s -L \
 # Verify checksum
 echo "Verifying md5 checksum from rootfs"
 if [ "$(md5sum /tmp/mos-update/update/rootfs | awk '{print $1}')" != "$(cat /tmp/mos-update/update/rootfs.md5)" ] ; then
-  echo "rootfs checksum error"
+  echo '{"message":"rootfs checksum error, aborting MOS update","priority":"alert"}' | nc -U /run/mos-notify.sock
   rm -rf /tmp/mos-update/update
   exit 1
 else
@@ -196,7 +201,7 @@ if [ "$UPDATE_KERNEL" = "true" ] ; then
   # Verify checksum from image
   echo "Verifying md5 checksum from Kernel image"
   if [ "$(md5sum /tmp/mos-update/update/image | awk '{print $1}')" != "$(cat /tmp/mos-update/update/image.md5)" ] ; then
-    echo "ERROR: Kernel image checksum error, not updating Kernel"
+    echo '{"message":"Kernel image checksum error, not updating Kernel","priority":"warning"}' | nc -U /run/mos-notify.sock
     rm -f /tmp/mos-update/update/image* /tmp/mos-update/update/drivers*
     UPDATE_KERNEL="false"
   else
@@ -206,7 +211,7 @@ if [ "$UPDATE_KERNEL" = "true" ] ; then
   # Verify checksum from drivers
   echo "Verifying md5 checksum from Kernel drivers"
   if [ "$(md5sum /tmp/mos-update/update/drivers | awk '{print $1}')" != "$(cat /tmp/mos-update/update/drivers.md5)" ] ; then
-    echo "ERROR: Kernel drivers checksum error, not updating Kernel"
+    echo '{"message":"Kernel drivers checksum error, not updating Kernel","priority":"warning"}' | nc -U /run/mos-notify.sock
     rm -f /tmp/mos-update/update/image* /tmp/mos-update/update/drivers*
     UPDATE_KERNEL="false"
   else
@@ -214,27 +219,4 @@ if [ "$UPDATE_KERNEL" = "true" ] ; then
   fi
 fi
 
-# Get rollback version
-ROLLBACK_VERSION=$(jq -r '"\(.mos.version)-\(.mos.channel)"' /boot/rollback/mos-release.json 2>/dev/null)
-
-# Check if rollback version is the same as installed version
-if [ "$CURRENT_VERSION" != "$ROLLBACK_VERSION" ] ; then
-  echo "Moving current MOS version to /boot/rollback"
-  if [ ! -d /boot/rollback ] ; then
-    mkdir -p /boot/rollback >/dev/null 2>&1
-  else
-    rm -rf /boot/rollback/*
-  fi
-
-  mv /boot/rootfs* /boot/rollback/
-  cp /etc/mos-release.json /boot/rollback/
-  mv /tmp/mos-update/update/rootfs* /boot/
-
-  if [ "$UPDATE_KERNEL" = "true" ] ; then
-    echo "Moving Kernel image and drivers to /boot/rollback"
-    mv /boot/image* /boot/drivers* /boot/rollback/
-    mv /tmp/mos-update/update/image* /tmp/mos-update/update/drivers* /boot/
-  fi
-else
-  echo "INFO: Rollback MOS version already in palce"
-fi
+echo '{"message":"MOS update done, please reboot","priority":"nromal"}' | nc -U /run/mos-notify.sock
